# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resonite_io/v1/session.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("PingRequest", "PingResponse", "SessionBase", "SessionStub")

from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ...message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpclib.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class PingRequest(betterproto2.Message):
    """
    PingRequest はクライアントが任意のメッセージ文字列を送信する。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("resonite_io.v1", "PingRequest", PingRequest)


@dataclass(eq=False, repr=False)
class PingResponse(betterproto2.Message):
    """
    PingResponse はサーバが受信したメッセージをそのまま返し、サーバ側で測定した
    Unix epoch (ナノ秒) を付与する。クライアントは RTT の概算と clock skew の
    観測に利用できる。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    server_unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)


default_message_pool.register_message("resonite_io.v1", "PingResponse", PingResponse)


class SessionStub(betterproto2_grpclib.ServiceStub):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(
        self,
        message: "PingRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "PingResponse":
        return await self._unary_unary(
            "/resonite_io.v1.Session/Ping",
            message,
            PingResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SessionBase(betterproto2_grpclib.ServiceBase):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(self, message: "PingRequest") -> "PingResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_ping(
        self, stream: "grpclib.server.Stream[PingRequest, PingResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.ping(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Session/Ping": grpclib.const.Handler(
                self.__rpc_ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                PingRequest,
                PingResponse,
            ),
        }
