# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: resonite_io/v1/camera.proto, resonite_io/v1/session.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "CameraBase",
    "CameraFrame",
    "CameraFrameFormat",
    "CameraStreamRequest",
    "CameraStub",
    "PingRequest",
    "PingResponse",
    "SessionBase",
    "SessionStub",
)

from collections.abc import AsyncIterator
from dataclasses import dataclass
from typing import TYPE_CHECKING

import betterproto2
import grpclib
from betterproto2 import grpclib as betterproto2_grpclib

from ...message_pool import default_message_pool

if TYPE_CHECKING:
    import grpclib.server
    from betterproto2.grpclib.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


class CameraFrameFormat(betterproto2.Enum):
    """
    CameraFrameFormat は pixels の byte 配置を識別する。
    """

    UNSPECIFIED = 0

    BGRA8 = 1
    """
    BGRA8: 1 ピクセル 4 byte (B, G, R, A の順)、row 0 = 画像上端 (top-left origin)。
    """

    @classmethod
    def betterproto_value_to_renamed_proto_names(cls) -> dict[int, str]:
        return {
            0: "CAMERA_FRAME_FORMAT_UNSPECIFIED",
            1: "CAMERA_FRAME_FORMAT_BGRA8",
        }

    @classmethod
    def betterproto_renamed_proto_names_to_value(cls) -> dict[str, int]:
        return {
            "CAMERA_FRAME_FORMAT_UNSPECIFIED": 0,
            "CAMERA_FRAME_FORMAT_BGRA8": 1,
        }


@dataclass(eq=False, repr=False)
class CameraFrame(betterproto2.Message):
    """
    CameraFrame は 1 フレーム分の raw pixel と metadata。
    pixels の長さは必ず width * height * 4 (BGRA8 時)。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    format: "CameraFrameFormat" = betterproto2.field(
        3, betterproto2.TYPE_ENUM, default_factory=lambda: CameraFrameFormat(0)
    )

    unix_nanos: "int" = betterproto2.field(4, betterproto2.TYPE_INT64)

    frame_id: "int" = betterproto2.field(5, betterproto2.TYPE_INT64)

    pixels: "bytes" = betterproto2.field(6, betterproto2.TYPE_BYTES)


default_message_pool.register_message("resonite_io.v1", "CameraFrame", CameraFrame)


@dataclass(eq=False, repr=False)
class CameraStreamRequest(betterproto2.Message):
    """
    CameraStreamRequest はストリーム開始時に解像度と fps 上限を指定する。
    width/height が 0 以下のときはサーバ既定 (640x480) を使う。
    fps_limit が 0 以下のときは pacing 無し (ベストエフォートのネイティブ fps)。
    """

    width: "int" = betterproto2.field(1, betterproto2.TYPE_INT32)

    height: "int" = betterproto2.field(2, betterproto2.TYPE_INT32)

    fps_limit: "float" = betterproto2.field(3, betterproto2.TYPE_FLOAT)


default_message_pool.register_message(
    "resonite_io.v1", "CameraStreamRequest", CameraStreamRequest
)


@dataclass(eq=False, repr=False)
class PingRequest(betterproto2.Message):
    """
    PingRequest はクライアントが任意のメッセージ文字列を送信する。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)


default_message_pool.register_message("resonite_io.v1", "PingRequest", PingRequest)


@dataclass(eq=False, repr=False)
class PingResponse(betterproto2.Message):
    """
    PingResponse はサーバが受信したメッセージをそのまま返し、サーバ側で測定した
    Unix epoch (ナノ秒) を付与する。クライアントは RTT の概算と clock skew の
    観測に利用できる。
    """

    message: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    server_unix_nanos: "int" = betterproto2.field(2, betterproto2.TYPE_INT64)


default_message_pool.register_message("resonite_io.v1", "PingResponse", PingResponse)


class CameraStub(betterproto2_grpclib.ServiceStub):
    """
    Camera は映像モダリティの中心サービス。
    """

    async def stream_frames(
        self,
        message: "CameraStreamRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "AsyncIterator[CameraFrame]":
        async for response in self._unary_stream(
            "/resonite_io.v1.Camera/StreamFrames",
            message,
            CameraFrame,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        ):
            yield response


class SessionStub(betterproto2_grpclib.ServiceStub):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(
        self,
        message: "PingRequest",
        *,
        timeout: "float | None" = None,
        deadline: "Deadline | None" = None,
        metadata: "MetadataLike | None" = None,
    ) -> "PingResponse":
        return await self._unary_unary(
            "/resonite_io.v1.Session/Ping",
            message,
            PingResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class CameraBase(betterproto2_grpclib.ServiceBase):
    """
    Camera は映像モダリティの中心サービス。
    """

    async def stream_frames(
        self, message: "CameraStreamRequest"
    ) -> "AsyncIterator[CameraFrame]":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)
        yield CameraFrame()

    async def __rpc_stream_frames(
        self, stream: "grpclib.server.Stream[CameraStreamRequest, CameraFrame]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        await self._call_rpc_handler_server_stream(
            self.stream_frames,
            stream,
            request,
        )

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Camera/StreamFrames": grpclib.const.Handler(
                self.__rpc_stream_frames,
                grpclib.const.Cardinality.UNARY_STREAM,
                CameraStreamRequest,
                CameraFrame,
            ),
        }


class SessionBase(betterproto2_grpclib.ServiceBase):
    """
    Session は制御プレーンの中心サービス。モダリティ固有の RPC は別 service に
    分割するため、本 service は接続確認と将来的な capability negotiation のみを
    担当する。
    """

    async def ping(self, message: "PingRequest") -> "PingResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_ping(
        self, stream: "grpclib.server.Stream[PingRequest, PingResponse]"
    ) -> None:
        request = await stream.recv_message()
        assert request is not None
        response = await self.ping(request)
        await stream.send_message(response)

    def __mapping__(self) -> "dict[str, grpclib.const.Handler]":
        return {
            "/resonite_io.v1.Session/Ping": grpclib.const.Handler(
                self.__rpc_ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                PingRequest,
                PingResponse,
            ),
        }
